USE sucos;

SELECT * FROM tb_produtos;

-- ADICIONANDO A PRIMARY KEY NA COLUNA JA EXISTENTE 

ALTER TABLE tb_produtos ADD PRIMARY KEY (COD);

ALTER TABLE tb_vendedores ADD PRIMARY KEY (MATRICULA);

ALTER TABLE tb_cliente ADD PRIMARY KEY (CPF);

-- SE FOR ADICIONAR UM ITEM QUE JA TENHA NO REGISTRO ELE NAO VAI PERMITIR, VAI MOSTRAR DUPLICAÇÃO
INSERT INTO tb_produtos (
COD,NomeProduto, SABOR, TAMANHO) VALUES (
1088127 , 'agua do verao', 'agua de coco', 'G');