USE sucos;

SELECT * FROM tb_produtos;

-- ADICIONANDO A PRIMARY KEY NA COLUNA JA EXISTENTE 

ALTER TABLE tb_produtos ADD PRIMARY KEY (COD);

ALTER TABLE tb_vendedores ADD PRIMARY KEY (MATRICULA);

ALTER TABLE tb_cliente ADD PRIMARY KEY (CPF);