
-- CRIANDO BANCO DE DADOS
CREATE DATABASE SUCOS;

-- ANTES DE CRIAR TABELA É NECESSARIO ENTRAR NO BANCO DE DADOS
USE SUCOS;

-- CRIANDO TABELA DE VENDEDORES
CREATE TABLE Tb_VENDEDORES 
(NOME VARCHAR (100),
MATRICULA VARCHAR (5),
PERCENTUAL_COMISSAO FLOAT);

-- CRIANDO TABELA DE CLIENTES
CREATE TABLE Tb_Cliente
(NomeCliente VARCHAR (100),
CPF INT ,
IDADE SMALLINT ,
SEXO BIT (1));

-- CRIANDO TABELA DE PRODUTOS
CREATE TABLE Tb_Produtos
(COD INT ,
NomeProduto VARCHAR (20),
SABOR VARCHAR (20),
TAMANHO ENUM ('P','M','G'),
PRECO FLOAT (2,2));


-- ANTES DE COMEÇAR A INSERIR CERTIFIQUE-SE DE ESTA USANDO O BANCO DE DADOS CORRETO
USE sucos;

-- INSERIR DADOS NAS TABELAS DE PRODUTOS  (ORDEM DE COLUNAS E RESPEITANDO A ORDEM INSERE OS VALORES 
INSERT INTO tb_produtos (
COD, NomeProduto, SABOR, TAMANHO) VALUES (
1040107, 'Ligth', 'Melancia', 'P');

-- INSERINDO APENAS UM REGISTRO DA COLUNA 
INSERT INTO tb_produtos (
PRECO)  VALUES (8.50);

-- INSERINDO OUTROS DADOS À TABELA DE PRODUTOS
INSERT INTO tb_produtos (
COD, NomeProduto, SABOR, TAMANHO, PRECO) VALUES (
1037797, 'Clean', 'Laranja', 'P', 10.00);

-- INSERIR DADOS NAS TABELAS DE VENDEDORES 
INSERT INTO tb_vendedores
( NOME, MATRICULA, PERCENTUAL_COMISSAO)
VALUES
('João Geraldo da Fonseca', '00233', 0.10);

INSERT INTO tb_vendedores
( NOME, MATRICULA, PERCENTUAL_COMISSAO)
VALUES
('Beatriz Marcela dos santos', '00234', 0.12);

INSERT INTO tb_vendedores
( NOME, MATRICULA, PERCENTUAL_COMISSAO)
VALUES
('Rodrigo Santiago de Freitas', '00235', 0.9);


-- CONSULTANDO ITENS DA TABELA PRODUTOS
SELECT * FROM tb_produtos;

-- CONSULTANDO ITENS DA TABELA VENDEDORES
SELECT * FROM tb_vendedores;


